### ISSUE TITLE
Get Too Short to 4D DCM Images

### ISSUE THREAD

**Issue by Maximiliun** [mslw/osirix-bids-output#7]
Dear Prof. Michał Szczepanik,

Many thanks for bringing BIDS to HOROS / Osirix users.

I can perform the transformation of Structural acquisitions into BDIS using your plug-in.

But I still have the "Too Short" answer for all my functional  TASK and RESTING sequences.

Probably because my scanner (Philips Achieva) save as  4D  dcm file that consist of only one (big) file.

What would be the best solution to this problem?

Thank you very much for your attention,

Francisco Salido (@Maximiliun).

**Comment by Maximiliun** [comment]
found the result table:
[export_2018-07-17_225653.csv.txt](https://github.com/mslw/horos-bids-output/files/2204184/export_2018-07-17_225653.csv.txt)

**Comment by mslw** [comment]
Hi. Thank you for trying out the plugin.

I am afk until the end of July, so I won't be able to take a closer look until then.

This may indeed be Phillips specific (I only tested on scans from Siemens Trio).

The bold series is discarded with "too short" comment if it has less images than specified in the General Mapping Window (the first one) - this feature was added to easily discard scans that were interrupted at the beginning. 

I would expect that "Too short" should not happen with "minimum bold images" set to 0 (default).

If you set it to 0 and it still happens, then the question is what is the Horos' numberOfImages property of your 4D Dicom Series. I'm not sure about this, but Horos probably shows this somewhere if you expand a study. The check for "too short" is done as follows:
```
if ([[[decoratedSeries series] numberOfImages] isLessThan:minimum]){
    [decoratedSeries setDiscard:YES];
    [decoratedSeries setValue:@"TooShort" forKey:@"comment"];
                }
```

BTW, I'm not a Prof. 😊 And sorry for closing and immediately re-opening the issue, I hit the wrong button. 

Best, 
Michał

**Comment by mslw** [comment]
Were you able to follow up on this issue? Specifically:
- Does "Too short" still happen when you set "minimum bold images" in the General Mapping Window to 0?
- What is the number shown by Horos in the "#im" column for your fMRI series?
- Are you able to share an example 4D DICOM from your scanner? Ideally phantom data, so there would be no privacy concerns.

As I wrote previously, I guess that this is caused either by the user of the plugin entering a number which is bigger than the number of images, or by Horos incorrectly reporting the number of images.

By the way: be advised that the plugin would only handle field maps consisting of one magnitude and two phase difference images. I noticed that there are no field map files in your export summary, but if there were, it could be another area of incompatibility for Philips data.

**Comment by sarahi03** [comment]
123/5000
I can not rename the subjects, it keeps taking the original name from the dicom, I tried with all the examples of the "Subject & sessions rules"

**Comment by mslw** [comment]
Hi @sarahi03 

This is weird - can you provide an example, i. e. Patient Name from dicom and the strings you enter in Subject & session rules (Pattern, Subject label, Session label)?

Most likely there is some small mistake in the regular expression. If the expression does not match the Patient Name, the plugin will use the full Patient Name from dicom.

And just to get the simplest explanation out of the way - if you are looking at the Mapping Summary Window (the one with _Export to BIDS_ button), make sure to look at _BIDS Path_, not the _Subject_ column to check the result (as the _Subject_ column lists names from dicoms) - this puzzled me for a while when I was testing the plugin before last release.
